#use with docker-compose-dev.yml

FROM node:14.15.3-alpine
WORKDIR /usr/app

COPY package.json ./package.json

RUN npm set progress=false && \
    npm config set depth 0 && \
    npm install && \
    npm cache verify

COPY . ./
