
  export const violationsTableColsMap = new Map([
  ["id","Violation ID"],
  ["address","Address"],
  ["unit","Unit"],
  ["story","Story"],
  ["class","Class"],
  ["inspectionDate","Inspection Date"],
  ["approvedDate","Approved Date"],
  ["originalCertifyByDate","Original Certify-By Date"],
  ["originalCorrectByDate","Original Correct-By Date"],
  ["certifiedDate","Certified Date"],
  ["description","Description"],
  ["issuedDate","Issue Date"],
  ["currentStatus","Current Status"],
  ["currentStatusDate","Current Status Date"],
  ["type","Type"],
  ["violationStatus","Violation Status"],
  ["neighborhood","Neighborhood"]
  ]);

  export const complaintsTableColsMap = new Map([
  ["problemId", "Problem ID"],
  ["complaintId", "Complaint ID"],
  ["buildingId", "Building ID"],
  ["address","Address"],
  ["unit", "Unit"],
  ["receivedDate", "Received Date"],
  ["status", "Status"],
  ["statusDate", "Status Date"],
  ["unitType", "Unit Type"],
  ["spaceType", "Space Type"],
  ["type", "Type"],
  ["category", "Category"],
  ["issue", "Issue"],
  ["statusDescription", "Status Description"]
  ]);

  export const testData = `{
  "violations": [
  {
  "id": "12421730",
  "address": "395 SOUTH END AVENUE, MANHATTAN 10280",
  "unit": "12L",
  "story": "12",
  "class": "A",
  "inspectionDate": "2018-06-07",
  "approvedDate": "2018-06-08",
  "originalCertifyByDate": "2018-09-28",
  "originalCorrectByDate": "2018-09-14",
  "newCertifyByDate": "",
  "newCorrectByDate": "",
  "certifiedDate": "2018-06-27",
  "description": "SECTION 27-2013 ADM CODE  PAINT WITH LIGHT COLORED PAINT TO THE SATISFACTION OF THIS DEPARTMENT AT CEILING  IN THE BATHROOM  LOCATED AT APT 12L, 12th STORY, 2nd APARTMENT FROM WEST AT NORTH",
  "issuedDate": "2018-06-11",
  "currentStatus": "VIOLATION DISMISSED",
  "currentStatusDate": "2018-09-07",
  "type": "Original",
  "violationStatus": "Close",
  "neighborhood": "Battery Park City-Lower Manhattan"
  },
  {
  "id": "12319342",
  "address": "395 SOUTH END AVENUE, MANHATTAN 10280",
  "unit": "19K",
  "story": "18",
  "class": "B",
  "inspectionDate": "2018-04-03",
  "approvedDate": "2018-04-04",
  "originalCertifyByDate": "2018-05-24",
  "originalCorrectByDate": "2018-05-10",
  "newCertifyByDate": "",
  "newCorrectByDate": "",
  "certifiedDate": "2019-03-13",
  "description": "SECTION  27-2005 HMC:TRACE AND REPAIR THE SOURCE AND ABATE THE NUISANCE CONSISTING OF MOLD ... AT CEILING (APPROX 1 SQ FT)  IN THE BATHROOM  LOCATED AT APT 19K, 18th STORY, 1st APARTMENT FROM WEST AT NORTH",
  "issuedDate": "2018-04-05",
  "currentStatus": "NOV CERTIFIED LATE",
  "currentStatusDate": "2019-03-13",
  "type": "Original",
  "violationStatus": "Open",
  "neighborhood": "Battery Park City-Lower Manhattan"
  },
  {
  "id": "12319348",
  "address": "395 SOUTH END AVENUE, MANHATTAN 10280",
  "unit": "19K",
  "story": "18",
  "class": "B",
  "inspectionDate": "2018-04-03",
  "approvedDate": "2018-04-04",
  "originalCertifyByDate": "2018-05-24",
  "originalCorrectByDate": "2018-05-10",
  "newCertifyByDate": "",
  "newCorrectByDate": "",
  "certifiedDate": "2018-04-17",
  "description": "SECTION 27-2005, 2007 ADM CODE  ARRANGE AND MAKE SELF-CLOSING THE DOORS IN THE ENTRANCE  LOCATED AT APT 19K, 18th STORY, 1st APARTMENT FROM WEST AT NORTH",
  "issuedDate": "2018-04-05",
  "currentStatus": "VIOLATION DISMISSED",
  "currentStatusDate": "2018-06-28",
  "type": "Original",
  "violationStatus": "Close",
  "neighborhood": "Battery Park City-Lower Manhattan"
  },
  {
  "id": "12319670",
  "address": "395 SOUTH END AVENUE, MANHATTAN 10280",
  "unit": "19K",
  "story": "18",
  "class": "A",
  "inspectionDate": "2018-04-03",
  "approvedDate": "2018-04-04",
  "originalCertifyByDate": "2018-07-23",
  "originalCorrectByDate": "2018-07-09",
  "newCertifyByDate": "",
  "newCorrectByDate": "",
  "certifiedDate": "2018-04-17",
  "description": "SECTION 27-2013 ADM CODE  PAINT WITH LIGHT COLORED PAINT TO THE SATISFACTION OF THIS DEPARTMENT AT CEILING  IN THE BATHROOM  LOCATED AT APT 19K, 18th STORY, 1st APARTMENT FROM WEST AT NORTH",
  "issuedDate": "2018-04-05",
  "currentStatus": "VIOLATION DISMISSED",
  "currentStatusDate": "2018-06-28",
  "type": "Original",
  "violationStatus": "Close",
  "neighborhood": "Battery Park City-Lower Manhattan"
  }],
  "complaints": [
    {
      "complaintId": "6901315",
      "problemId": "14377275",
      "buildingId": "805311",
      "address": "395 SOUTH END AVENUE, MANHATTAN 10280",
      "unit": "14F",
      "receivedDate": "2014-04-28",
      "status": "CLOSE",
      "statusDate": "2014-07-31",
      "unitType": "APARTMENT",
      "spaceType": "BATHROOM",
      "type": "NON EMERGENCY",
      "category": "GENERAL - VENTILATION SYSTEM",
      "issue": "BROKEN OR MISSING",
      "statusDescription": "The Department of Housing Preservation and Development inspected the following conditions. Violations were issued. Information about specific violations is available at www.nyc.gov/hpd."
      },
      {
      "complaintId": "6901315",
      "problemId": "14377276",
      "buildingId": "805311",
      "address": "395 SOUTH END AVENUE, MANHATTAN 10280",
      "unit": "14F",
      "receivedDate": "2014-04-28",
      "status": "CLOSE",
      "statusDate": "2014-07-31",
      "unitType": "APARTMENT",
      "spaceType": "OTHER ROOM/AREA",
      "type": "NON EMERGENCY",
      "category": "GENERAL - VENTILATION SYSTEM",
      "issue": "BROKEN OR MISSING",
      "statusDescription": "The Department of Housing Preservation and Development inspected the following conditions. Violations were previously issued for these conditions. Information about specific violations is available at www.nyc.gov/hpd."
      },
      {
      "complaintId": "6901315",
      "problemId": "14377277",
      "buildingId": "805311",
      "address": "395 SOUTH END AVENUE, MANHATTAN 10280",
      "unit": "14F",
      "receivedDate": "2014-04-28",
      "status": "CLOSE",
      "statusDate": "2014-07-31",
      "unitType": "APARTMENT",
      "spaceType": "KITCHEN",
      "type": "NON EMERGENCY",
      "category": "GENERAL - VENTILATION SYSTEM",
      "issue": "BROKEN OR MISSING",
      "statusDescription": "The Department of Housing Preservation and Development inspected the following conditions. No violations were issued. The complaint has been closed."
      },
      {
      "complaintId": "7032100",
      "problemId": "14712886",
      "buildingId": "805311",
      "address": "395 SOUTH END AVENUE, MANHATTAN 10280",
      "unit": "12L",
      "receivedDate": "2014-10-02",
      "status": "CLOSE",
      "statusDate": "2015-01-06",
      "unitType": "APARTMENT",
      "spaceType": "BATHROOM",
      "type": "EMERGENCY",
      "category": "WATER LEAK - HEAVY FLOW",
      "issue": "AT WALL OR CEILING",
      "statusDescription": "The Department of Housing Preservation and Development contacted an occupant of the apartment and verified that the following conditions were corrected. The complaint has been closed. If the condition still exists, please file a new complaint."
      },
      {
      "complaintId": "7090466",
      "problemId": "14820939",
      "buildingId": "805311",
      "address": "395 SOUTH END AVENUE, MANHATTAN 10280",
      "unit": "12L",
      "receivedDate": "2014-11-10",
      "status": "CLOSE",
      "statusDate": "2015-07-31",
      "unitType": "APARTMENT",
      "spaceType": "BATHROOM",
      "type": "NON EMERGENCY",
      "category": "WATER LEAK - DAMP SPOT",
      "issue": "FROM WALL OR CEILING",
      "statusDescription": "The Department of Housing Preservation and Development contacted an occupant of the apartment and verified that the following conditions were corrected. The complaint has been closed. If the condition still exists, please file a new complaint."
      },
      {
      "complaintId": "7091211",
      "problemId": "14822200",
      "buildingId": "805311",
      "address": "395 SOUTH END AVENUE, MANHATTAN 10280",
      "unit": "12L",
      "receivedDate": "2014-11-11",
      "status": "CLOSE",
      "statusDate": "2014-11-17",
      "unitType": "APARTMENT",
      "spaceType": "BATHROOM",
      "type": "NON EMERGENCY",
      "category": "WATER LEAK - SLOW LEAK",
      "issue": "AT WALL OR CEILING",
      "statusDescription": "The Department of Housing Preservation and Development contacted an occupant of the apartment and verified that the following conditions were corrected. The complaint has been closed. If the condition still exists, please file a new complaint."
      },
      {
      "complaintId": "7091211",
      "problemId": "14822201",
      "buildingId": "805311",
      "address": "395 SOUTH END AVENUE, MANHATTAN 10280",
      "unit": "12L",
      "receivedDate": "2014-11-11",
      "status": "CLOSE",
      "statusDate": "2015-07-31",
      "unitType": "APARTMENT",
      "spaceType": "BATHROOM",
      "type": "NON EMERGENCY",
      "category": "PAINT/PLASTER - CEILING",
      "issue": "DIRTY OR UNSANITARY",
      "statusDescription": "The Department of Housing Preservation and Development contacted an occupant of the apartment and verified that the following conditions were corrected. The complaint has been closed. If the condition still exists, please file a new complaint."
      },
      {
      "complaintId": "7211592",
      "problemId": "15023066",
      "buildingId": "805311",
      "address": "395 SOUTH END AVENUE, MANHATTAN 10280",
      "unit": "6N",
      "receivedDate": "2015-01-10",
      "status": "CLOSE",
      "statusDate": "2015-01-16",
      "unitType": "APARTMENT",
      "spaceType": "ENTIRE APARTMENT",
      "type": "EMERGENCY",
      "category": "HEAT/HOT WATER - ENTIRE BUILDING",
      "issue": "NO HEAT",
      "statusDescription": "The Department of Housing Preservation and Development responded to a complaint of no heat or hot water and was advised by a tenant in the building that heat and hot water had been restored. If the condition still exists, please file a new complaint."
      }
  ]
}`
